<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\hexArch\domain\Domain.csproj" />
    <ProjectReference Include="..\hexArch\application\Application.csproj" />
    <ProjectReference Include="..\hexArch\data\Data.csproj" />
    <ProjectReference Include="..\hexArch\repository\Repository.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
